#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Get current branch
branch=`git rev-parse --abbrev-ref HEAD`

# Extract issue from branch name (if exists)
regex=".*-([0-9]*)-.*"
[[ $branch =~ $regex ]]
issue="${BASH_REMATCH[1]}"

# If $issue was found in branch and isn't found in commit message, append to end of commit message
if [ ! -z $issue ] && ! grep -q $issue $1 
then
    echo "\nRefer to issue #$issue" >> $1
fi

exit 0
