#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[0;31m'
NC='\033[0m'
branch="$(git rev-parse --abbrev-ref HEAD)"

# Configure Branch Naming Convention
BRANCH_TYPES="feat|fix|tmp"
MIN_BRANCH_LENGTH=5
MAX_BRANCH_LENGTH=50

valid_branch_regex="^($BRANCH_TYPES)\/[a-z0-9#-]{$MIN_BRANCH_LENGTH,$MAX_BRANCH_LENGTH}$"
branch_naming_convention="Branch naming convention

               [type*]/[group]-#[issue]-[description*]

   - type: task type ($BRANCH_TYPES)
   - group (optional): task group
   - issue (optional): task ID from tracker
   - description: short task description
   - only lowercase letters, numbers, and '-'s
   - length between $MIN_BRANCH_LENGTH and $MAX_BRANCH_LENGTH characters
"

# Forbid committing to main
if [ "$branch" = "main" ]; then
  echo "❌ ${RED}Forbidden to commit to main branch. Please create branch and work there.${NC}
  $branch_naming_convention
   Example            
                    git checkout -b feat/ui-#12-add-dark-mode\n"
  exit 1
fi

# Enforce branch naming policy
if [[ ! $branch =~ $valid_branch_regex ]]
then
    echo "❌ ${RED}Invalid branch name. Please rename your branch adhearing to the following convention.${NC}
   $branch_naming_convention
    Example
                          git branch -m feat/ui-#12-add-dark-mode\n"
    exit 1
fi

exit 0
