#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

RED='\033[0;31m'
NC='\033[0m'
branch="$(git rev-parse --abbrev-ref HEAD)"

branch_types="feat|fix|tmp"
min_branch_length=5
max_branch_length=50
valid_branch_regex="^($branch_types)\/[a-z0-9#-]{$min_branch_length,$max_branch_length}$"
branch_naming_convention="Branch naming convention

               [type*]/[group]-#[issue]-[description*]

   - type: task type ($branch_types)
   - group (optional): task group
   - issue (optional): task ID from tracker
   - description: short task description
   - only lowercase letters, numbers, and '-'s
   - length between $min_branch_length and $max_branch_length characters
"

# Forbid committing to main
if [ "$branch" = "main" ]; then
  echo "❌ ${RED}Forbidden to commit to main branch. Please create branch and work there.${NC}
  $branch_naming_convention
   Example            
                    git checkout -b feat/ui-#12-add-dark-mode\n"
  exit 1
fi

# Enforce branch naming policy
if [[ ! $branch =~ $valid_branch_regex ]]
then
    echo "❌ ${RED}Invalid branch name. Please rename your branch adhearing to the following convention.${NC}
   $branch_naming_convention
    Example
                          git branch -m feat/ui-#12-add-dark-mode\n"
    exit 1
fi

exit 0
